volumes:
  vendor-data:
    driver: local

services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - ./backend:/var/www/html
      - vendor-data:/var/www/html/vendor

  queue-worker:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/var/www/html
      - vendor-data:/var/www/html/vendor

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
