replicaCount: 2

image:
  repository: ghcr.io/REPLACE/app-backend
  tag: latest

frontend:
  image:
    repository: ghcr.io/REPLACE/app-frontend
    tag: latest

service:
  type: ClusterIP
  port: 80
